// Generated by npm run build; no secrets belong in this file.
window.SITE_CONFIG = {
  "siteUrl": "https://jeffreybowen.com",
  "googleBusinessProfileUrl": "",
  "googleReviewUrl": "",
  "bookingUrl": "",
  "formspreeEndpoint": "",
  "gaMeasurementId": "",
  "searchConsoleVerification": "",
  "publicOfficeAddress": "",
  "contactEmail": "Info@chelseaRealestate.com"
};
